id: rss_summarizer
namespace: main

tasks:
  - id: looper
    type: io.kestra.plugin.core.flow.ForEach
    # Store RSS_URLS in KV as a comma-separated string of feed URLs
    values: "{{ kv('RSS_URLS') | split(',') }}"
    tasks:
      - id: summarize_one
        type: io.kestra.plugin.core.flow.Subflow
        flowId: rss_single_summarizer
        namespace: main
        inputs:
          feedUrl: "{{ taskrun.value | trim }}"

triggers:
  - id: webhook
    type: io.kestra.plugin.core.trigger.Webhook
    key: "{{ secret('WEBHOOK_TRIGGER_KEY') }}"
